spring:
  #database info
  # 34.80.254.154
  # azhe2401 - root
  # 3306 - 3307
  datasource:
    url: jdbc:mariadb://localhost:3307/db1
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    #file upload info
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#MyBatis config
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#spring transactional log
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

server:
  address: 0.0.0.0
  port: 8080









# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.heima

knife4j:
  enable: true  # 开启knife4j接口文档美化
  setting:
    language: zh_cn # 指定语言


#  spring:
#    #database info
#    datasource:
#      url: jdbc:mysql://localhost:3306/db1
#      username: root
#      password: 1234
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      #file upload info
#    servlet:
#      multipart:
#        max-file-size: 10MB
#        max-request-size: 100MB
#  #MyBatis config
#  mybatis:
#    configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#      map-underscore-to-camel-case: true
#  #spring transactional log
#  logging:
#    level:
#      org.springframework.jdbc.support.JdbcTransactionManager: debug
#
#  server:
#    address: 0.0.0.0
#    port: 8080